[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_release]
command = "cargo"
args = ["build", "--release"]
dependencies = ["clean"]

[tasks.build-flow]
dependencies = [
    "format",
    "build_release",
]
