extend = [
    {path = "./makefiles/env.toml"},
    {path = "./makefiles/utils.toml"},
    {path = "./makefiles/benchmarks.toml"},
    {path = "./makefiles/plots.toml"},
]

# ---------------------------- General commands ----------------------------------

# Build whole project
[tasks.build]
dependencies = ["build-rust-queues", "build-c-msq", "build-c-lprq"]

# Clean whole project
[tasks.clean]
dependencies = ["clean-rust-queues", "clean-c-msq", "clean-c-lprq"]

# ---------------------------- MSQ benchmark commands ----------------------------

# Commands for MSQ pairwise benchmark
[tasks.benchmark-msq]
description = "Pairwise benchmark for MSQ (Rust vs. C)"
dependencies = ["pw-msq-c", "pw-msq-rust"]

# ---------------------------- LPRQ benchmark commands ---------------------------

# Commands for LPRQ pairwise benchmarks
[tasks.benchmark-lprq-pw]
description = "Pairwise benchmarks for LPRQ (Rust vs. C++)"
dependencies = ["pw-lprq-c", "pw-lprq-rust", "pw-lprq-arc", "pw-lprq-epoch"]

# Commands for LPRQ MPMC benchmarks
[tasks.benchmark-lprq-1-1]
description = "LPRQ benchmark MPMC 1:1 ratio"
dependencies = ["mpmc-lprq-c-1-1", "mpmc-lprq-rust-1-1", "mpmc-lprq-arc-1-1", "mpmc-lprq-epoch-1-1"]
[tasks.benchmark-lprq-2-1]
description = "LPRQ benchmark MPMC 2:1 ratio"
dependencies = ["mpmc-lprq-c-2-1", "mpmc-lprq-rust-2-1", "mpmc-lprq-arc-2-1"]
[tasks.benchmark-lprq-1-2]
description = "LPRQ benchmark MPMC 1:2 ratio"
dependencies = ["mpmc-lprq-c-1-2", "mpmc-lprq-rust-1-2", "mpmc-lprq-arc-1-2"]

[tasks.benchmark-lprq-mpmc]
description = "MPMC benchmarks for LPRQ (Rust vs. C++)"
dependencies = ["benchmark-lprq-1-1", "benchmark-lprq-2-1"]

# Commands to benchmark energy consumption with perf
[tasks.benchmark-energy-lprq-1-1]
dependencies = ["energy-c-1-1", "energy-rust-1-1", "energy-arc-1-1", "energy-epoch-1-1"]
[tasks.benchmark-energy-lprq-2-1]
dependencies = ["energy-c-2-1", "energy-rust-2-1", "energy-arc-2-1"]

# Command for both energy benchmarks
[tasks.benchmark-energy-lprq]
dependencies = ["benchmark-energy-lprq-1-1", "benchmark-energy-lprq-2-1"]

# Commands to benchmark memory access patterns with perf
[tasks.benchmark-perf-memory-lprq-1-1]
dependencies = ["memory-c-1-1", "memory-rust-1-1", "memory-arc-1-1", "memory-epoch-1-1"]
[tasks.benchmark-perf-memory-lprq-2-1]
dependencies = ["memory-c-2-1", "memory-rust-2-1", "memory-arc-2-1"]

# Commands to benchmark memory usage with memusage
[tasks.benchmark-memusage-lprq-1-1]
dependencies = ["memusage-c-1-1", "memusage-rust-1-1", "memusage-arc-1-1", "memusage-epoch-1-1"]
[tasks.benchmark-memusage-lprq-2-1]
dependencies = ["memusage-c-2-1", "memusage-rust-2-1", "memusage-arc-2-1"]

# Command for both memory benchmarks
[tasks.benchmark-memory-lprq]
dependencies = ["benchmark-perf-memory-lprq-1-1", "benchmark-perf-memory-lprq-2-1", "benchmark-memusage-lprq-1-1", "benchmark-memusage-lprq-2-1"]

# Command for all LPRQ benchmarks
[tasks.benchmark-lprq]
description = "All benchmarks for LPRQ"
dependencies = ["benchmark-lprq-pw", "benchmark-lprq-mpmc", "benchmark-energy-lprq", "benchmark-memory-lprq"]

# ---------------------------- Graphs and Tables commands ---------------------------

# Commands for MSQ graph
[tasks.graph-msq]
dependencies = ["_graph-pw-msq"]

# Command for LPRQ pw graph
[tasks.graph-lprq-pw]
dependencies = ["_graph-pw-lprq"]

# Commands for LPRQ MPMC graphs
[tasks.graph-lprq-1-1]
dependencies = ["_graph-mpmc-lprq-1-1"]
[tasks.graph-lprq-2-1]
dependencies = ["_graph-mpmc-lprq-2-1"]
[tasks.graph-lprq-1-2]
dependencies = ["_graph-mpmc-lprq-1-2"]

# Command for all LPRQ graphs
[tasks.graph-lprq]
description = "All graphs for LPRQ"
dependencies = ["graph-lprq-pw", "graph-lprq-1-1", "graph-lprq-2-1", "graph-lprq-1-2"]

# Generate all graphs
[tasks.graph-all]
description = "Graphs for all benchmarks"
dependencies = ["graph-msq", "graph-lprq"]

# Generate the tables
[tasks.create-tables]
description = "Tables from energy and memory benchmarks"
dependencies = ["_create-table"]

# ---------------------------- Final commands ---------------------------

# Tasks that generate the graph after sucessful benchmark

# MSQ flow
[tasks.msq]
dependencies = ["benchmark-msq", "graph-msq"]

# LPRQ flow
[tasks.lprq-pw]
dependencies = ["benchmark-lprq-pw", "graph-lprq-pw"]
[tasks.lprq-1-1]
dependencies = ["benchmark-lprq-1-1", "graph-lprq-1-1"]
[tasks.lprq-2-1]
dependencies = ["benchmark-lprq-2-1", "graph-lprq-2-1"]
[tasks.lprq-1-2]
dependencies = ["benchmark-lprq-1-2", "graph-lprq-1-2"]
[tasks.energy-lprq]
dependencies = ["benchmark-energy-lprq"]
[tasks.memory-lprq]
dependencies = ["benchmark-memory-lprq"]

# Commands to individuall benchmark alternative Rust solutions
[tasks.benchmark-hazp]
dependencies = ["pw-lprq-rust", "mpmc-lprq-rust-1-1", "mpmc-lprq-rust-2-1", "mpmc-lprq-rust-1-2", "energy-rust-1-1", "energy-rust-2-1", "memory-rust-1-1", "memory-rust-2-1", "memusage-rust-1-1", "memusage-rust-2-1"]
[tasks.benchmark-epoch]
dependencies = ["pw-lprq-epoch", "mpmc-lprq-epoch-1-1", "energy-epoch-1-1", "memory-epoch-1-1", "memusage-epoch-1-1"]
[tasks.benchmark-arc]
dependencies = ["pw-lprq-arc", "mpmc-lprq-arc-1-1", "mpmc-lprq-arc-2-1", "mpmc-lprq-arc-1-2", "energy-arc-1-1", "energy-arc-2-1", "memory-arc-1-1", "memory-arc-2-1", "memusage-arc-1-1", "memusage-arc-2-1"]
[tasks.benchmark-leaking]
dependencies = ["pw-lprq-leak", "mpmc-lprq-leak-1-1", "mpmc-lprq-leak-2-1", "mpmc-lprq-leak-1-2", "energy-leak-1-1", "energy-leak-2-1", "memory-leak-1-1", "memory-leak-2-1", "memusage-leak-1-1", "memusage-leak-2-1"]

# Benchmark all Rust versions
[tasks.benchmark-rust]
dependencies = ["benchmark-hazp", "benchmark-leaking", "benchmark-arc", "benchmark-epoch"]

# Run all benchmarks and generate all graphs and tables
[tasks.run]
description = "Run all benchmarks and generate all graphs"
dependencies = ["msq", "lprq-pw", "lprq-1-1", "lprq-2-1", "lprq-1-2", "energy-lprq", "memory-lprq", "create-tables"]
