extend = [
    {path = "./makefiles/utils.toml"},
    {path = "./makefiles/env.toml"},
    {path = "./makefiles/benchmarks.toml"},
    {path = "./makefiles/plots.toml"},
]

# Build whole project
[tasks.build]
dependencies = ["build-rust-queues", "build-c-msq", "build-c-lprq"]

# Clean whole project
[tasks.clean]
dependencies = ["clean-rust-queues", "clean-c-msq", "clean-c-lprq"]

# Runs all benchmarks and generate all graphs, might take some time
[tasks.run]
description = "Run all benchmarks and generate all graphs"
dependencies = ["benchmark", "graph-all"]

# Generate all graphs
[tasks.graph-all]
description = "Graphs for all benchmarks"
dependencies = ["graph-msq", "graph-lprq"]