[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt", "--", "--emit=files"]

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.build_debug]
command = "cargo"
args = ["build"]
dependencies = ["clean"]

[tasks.build]
dependencies = [
    "format",
    "build_debug",
]
