extend = [
    {path = "./makefiles/env.toml"},
    {path = "./makefiles/utils.toml"},
    {path = "./makefiles/benchmarks.toml"},
    {path = "./makefiles/plots.toml"},
]

# Build whole project
[tasks.build]
dependencies = ["build-rust-queues", "build-c-msq", "build-c-lprq"]

# Clean whole project
[tasks.clean]
dependencies = ["clean-rust-queues", "clean-c-msq", "clean-c-lprq"]

# Run all benchmarks for all queues
[tasks.benchmark]
description = "All benchmarks for all queues"
dependencies = ["benchmark-msq", "benchmark-lprq"]

# Generate all graphs
[tasks.graph-all]
description = "Graphs for all benchmarks"
dependencies = ["graph-msq", "graph-lprq"]

# Run all benchmarks and generate all graphs
[tasks.run]
description = "Run all benchmarks and generate all graphs"
dependencies = ["benchmark", "graph-all"]