extend = [
    {path = "./makefiles/env.toml"},
    {path = "./makefiles/utils.toml"},
    {path = "./makefiles/benchmarks.toml"},
    {path = "./makefiles/plots.toml"},
]

# Build whole project
[tasks.build]
dependencies = ["build-rust-queues", "build-c-msq", "build-c-lprq"]

# Clean whole project
[tasks.clean]
dependencies = ["clean-rust-queues", "clean-c-msq", "clean-c-lprq"]

# Commands for MSQ Pairwise benchmarks
[tasks.benchmark-pairwise-msq-t]
description = "Parameter scan over threads for pairwise MSQ"
dependencies = ["pairwise-msq-c-t", "pairwise-msq-rust-t"]
[tasks.benchmark-pairwise-msq-o]
description = "Parameter scan over operations for pairwise MSQ"
dependencies = ["pairwise-msq-c-o", "pairwise-msq-rust-o"]
[tasks.benchmark-pairwise-msq]
description = "Parameter scan for pairwise MSQ"
dependencies = ["benchmark-pairwise-msq-t", "benchmark-pairwise-msq-o"]

# Command for MSQ Pairwise benchmarks
[tasks.benchmark-msq]
description = "All benchmarks for MSQ"
dependencies = ["benchmark-pairwise-msq"]

# Commands for LPRQ Pairwise benchmarks
[tasks.benchmark-pairwise-lprq-t]
description = "Parameter scan over threads for pairwise LPRQ"
dependencies = ["pairwise-lprq-c-t", "pairwise-lprq-rust-t"]
[tasks.benchmark-pairwise-lprq-o]
description = "Parameter scan over operations for pairwise LPRQ"
dependencies = ["pairwise-lprq-c-o", "pairwise-lprq-rust-o"]
[tasks.benchmark-pairwise-lprq]
description = "Parameter scan for pairwise LPRQ"
dependencies = ["benchmark-pairwise-lprq-t", "benchmark-pairwise-lprq-o"]

# Commands for individual LPRQ MPMC ratios
[tasks.benchmark-mpmc-lprq-1-1]
description = "LPRQ benchmark MPMC 1:1 ratio"
dependencies = ["mpmc-lprq-c-1-1", "mpmc-lprq-rust-1-1"]
[tasks.benchmark-mpmc-lprq-1-2]
description = "LPRQ benchmark MPMC 1:2 ratio"
dependencies = ["mpmc-lprq-c-1-2", "mpmc-lprq-rust-1-2"]
[tasks.benchmark-mpmc-lprq-2-1]
description = "LPRQ benchmark MPMC 2:1 ratio"
dependencies = ["mpmc-lprq-c-2-1", "mpmc-lprq-rust-2-1"]

# Command for all LPRQ MPMC ratios
[tasks.benchmark-mpmc-lprq]
description = "MSQ benchmark MPM all ratios"
dependencies = ["benchmark-mpmc-lprq-1-1", "benchmark-mpmc-lprq-1-2", "benchmark-mpmc-lprq-2-1"]

# Command for LPRQ Pairwise and MPMC benchmarks
[tasks.benchmark-lprq]
description = "All benchmarks for LPRQ"
dependencies = ["benchmark-pairwise-lprq", "benchmark-mpmc-lprq"]

# Run all benchmarks for all queues
[tasks.benchmark-all]
description = "All benchmarks for all queues"
dependencies = ["benchmark-msq", "benchmark-lprq"]

# Command for MSQ Pairwise and MPMC graphs
[tasks.graph-msq]
description = "All graphs for MSQ"
dependencies = ["graph-pairwise-msq-t", "graph-pairwise-msq-o"]

# Command for LPRQ Pairwise and MPMC graphs
[tasks.graph-lprq]
description = "All graphs for LPRQ"
dependencies = ["graph-pairwise-lprq-t", "graph-pairwise-lprq-o", "graph-mpmc-lprq"]

# Commands to benchmark energy consumption for mpmc ratios
[tasks.benchmark-energy-1-1]
dependencies = ["energy-c-1-1", "energy-rust-1-1"]
[tasks.benchmark-energy-2-1]
dependencies = ["energy-c-2-1", "energy-rust-2-1"]

# Generate all graphs
[tasks.graph-all]
description = "Graphs for all benchmarks"
dependencies = ["graph-msq", "graph-lprq"]

# Tasks that generate the graph after a sucessful benchmark in both C and Rust.
[tasks.pw-msq-t]
dependencies = ["benchmark-pairwise-msq-t", "graph-pairwise-msq-t"]
private = true
[tasks.pw-msq-o]
dependencies = ["benchmark-pairwise-msq-o", "graph-pairwise-msq-o"]
private = true
[tasks.pw-lprq-t]
dependencies = ["benchmark-pairwise-lprq-t", "graph-pairwise-lprq-t"]
private = true
[tasks.pw-lprq-o]
dependencies = ["benchmark-pairwise-lprq-o", "graph-pairwise-lprq-o"]
private = true
[tasks.mpmc-lprq-1-1]
dependencies = ["benchmark-mpmc-lprq-1-1", "graph-mpmc-lprq-1-1"]
private = true
[tasks.mpmc-lprq-1-2]
dependencies = ["benchmark-mpmc-lprq-1-2", "graph-mpmc-lprq-1-2"]
private = true
[tasks.mpmc-lprq-2-1]
dependencies = ["benchmark-mpmc-lprq-2-1", "graph-mpmc-lprq-2-1"]
private = true

# Run all benchmarks and generate all graphs
[tasks.run]
description = "Run all benchmarks and generate all graphs"
dependencies = ["pw-msq-t", "pw-msq-o", "pw-lprq-t", "pw-lprq-o", "mpmc-lprq-1-1", "mpmc-lprq-1-2", "mpmc-lprq-2-1"]