extend = [
    {path = "./makefiles/env.toml"},
    {path = "./makefiles/utils.toml"},
    {path = "./makefiles/benchmarks.toml"},
    {path = "./makefiles/plots.toml"},
]

# ---------------------------- General commands ----------------------------------

# Build whole project
[tasks.build]
dependencies = ["build-rust-queues", "build-c-msq", "build-c-lprq"]

# Clean whole project
[tasks.clean]
dependencies = ["clean-rust-queues", "clean-c-msq", "clean-c-lprq"]

# ---------------------------- MSQ benchmark commands ----------------------------

# Commands for MSQ pairwise benchmarks
[tasks.benchmark-msq-pw]
description = "Parameter scan over threads for pairwise MSQ"
dependencies = ["pairwise-msq-c", "pairwise-msq-rust"]

# Command for MSQ pairwise congestion benchmark
[tasks.benchmark-msq-congestion]
dependencies = ["congestion-pairwise-msq-c", "congestion-pairwise-msq-rust"]

# Command for all MSQ benchmarks
[tasks.benchmark-msq]
description = "All benchmarks for MSQ"
dependencies = ["benchmark-msq-pw", "benchmark-msq-congestion"]

# ---------------------------- LPRQ benchmark commands ---------------------------

# Commands for LPRQ pairwise benchmarks
[tasks.benchmark-lprq-pw]
description = "Parameter scan over threads for pairwise LPRQ"
dependencies = ["pairwise-lprq-c", "pairwise-lprq-rust"]

# Command for LPRQ pairwise congestion benchmark
[tasks.benchmark-lprq-congestion-pw]
dependencies = ["congestion-pairwise-lprq-c", "congestion-pairwise-lprq-rust"]

# Commands for LPRQ MPMC congestion benchmarks
[tasks.benchmark-lprq-congestion-1-1]
dependencies = ["congestion-mpmc-c-1-1", "congestion-mpmc-rust-1-1"]
[tasks.benchmark-lprq-congestion-2-1]
dependencies = ["congestion-mpmc-c-2-1", "congestion-mpmc-rust-2-1"]

# Command for all LPRQ congestion benchmark
[tasks.benchmark-lprq-congestion]
dependencies = ["benchmark-lprq-congestion-pw", "benchmark-lprq-congestion-1-1", "benchmark-lprq-congestion-2-1"]

# Commands for LPRQ MPMC benchmarks
[tasks.benchmark-lprq-1-1]
description = "LPRQ benchmark MPMC 1:1 ratio"
dependencies = ["mpmc-lprq-c-1-1", "mpmc-lprq-rust-1-1"]
[tasks.benchmark-lprq-2-1]
description = "LPRQ benchmark MPMC 2:1 ratio"
dependencies = ["mpmc-lprq-c-2-1", "mpmc-lprq-rust-2-1"]

# Commands to benchmark energy consumption for mpmc ratios
[tasks.benchmark-energy-lprq-1-1]
dependencies = ["energy-c-1-1", "energy-rust-1-1"]
[tasks.benchmark-energy-lprq-2-1]
dependencies = ["energy-c-2-1", "energy-rust-2-1"]

# Command for both energy benchmarks
[tasks.benchmark-energy-lprq]
dependencies = ["benchmark-energy-lprq-1-1", "benchmark-energy-lprq-2-1"]

# Command for all LPRQ benchmarks
[tasks.benchmark-lprq]
description = "All benchmarks for LPRQ"
dependencies = ["benchmark-lprq-pw", "benchmark-lprq-congestion", "benchmark-energy-lprq"]

# ---------------------------- Graphs commands ---------------------------

# Commands for MSQ graphs
[tasks.graph-msq-pw]
dependencies = ["_graph-pairwise-msq"]
[tasks.graph-msq-congestion-pw]
dependencies = ["_graph-congestion-pairwise-msq"]

# Command for all MSQ graphs
[tasks.graph-msq]
dependencies = ["graph-msq-pw", "graph-msq-congestion-pw"]

# Command for LPRQ pairwise graph
[tasks.graph-lprq-pw]
dependencies = ["_graph-pairwise-lprq"]

# Commands for LPRQ MPMC graphs
[tasks.graph-lprq-1-1]
dependencies = ["_graph-mpmc-lprq-1-1"]
[tasks.graph-lprq-2-1]
dependencies = ["_graph-mpmc-lprq-2-1"]

# Commands for LPRQ congestion graphs
[tasks.graph-lprq-congestion-pw]
dependencies = ["_graph-congestion-pairwise-lprq"]
[tasks.graph-lprq-congestion-1-1]
dependencies = ["_graph-congestion-mpmc-1-1"]
[tasks.graph-lprq-congestion-2-1]
dependencies = ["_graph-congestion-mpmc-2-1"]
[tasks.graph-lprq-congestions]
dependencies = ["graph-lprq-congestion-pw", "graph-lprq-congestion-1-1", "graph-lprq-congestion-2-1"]

# Command for all LPRQ graphs
[tasks.graph-lprq]
description = "All graphs for LPRQ"
dependencies = ["graph-lprq-pw", "graph-lprq-1-1", "graph-lprq-2-1", "graph-lprq-congestions"]

# Command for MSQ and LPRQ congestion graphs
[tasks.graph-congestions]
dependencies = ["graph-msq-congestion-pw", "graph-lprq-congestion-pw", "graph-lprq-congestion-1-1", "graph-lprq-congestion-2-1"]

# Generate all graphs
[tasks.graph-all]
description = "Graphs for all benchmarks"
dependencies = ["graph-msq", "graph-lprq", "graph-congestions"]

# ---------------------------- Final commands ---------------------------

# Tasks that generate the graph after sucessful benchmark
[tasks.msq-pw]
dependencies = ["benchmark-msq-pw", "graph-msq-pw"]
[tasks.msq-congestion-pw]
dependencies = ["benchmark-msq-congestion", "graph-msq-congestion-pw"]
[tasks.lprq-pw]
dependencies = ["benchmark-lprq-pw", "graph-lprq-pw"]
[tasks.lprq-1-1]
dependencies = ["benchmark-lprq-1-1", "graph-lprq-1-1"]
[tasks.lprq-2-1]
dependencies = ["benchmark-lprq-2-1", "graph-lprq-2-1"]
[tasks.lprq-congestion-pw]
dependencies = ["benchmark-lprq-congestion-pw", "graph-lprq-congestion-pw"]
[tasks.lprq-congestion-1-1]
dependencies = ["benchmark-lprq-congestion-1-1", "graph-lprq-congestion-1-1"]
[tasks.lprq-congestion-2-1]
dependencies = ["benchmark-lprq-congestion-2-1", "graph-lprq-congestion-2-1"]
[tasks.energy-lprq]
dependencies = ["benchmark-energy-lprq"]

# Run all benchmarks and generate all graphs
[tasks.run]
description = "Run all benchmarks and generate all graphs"
dependencies = ["msq-pw", "lprq-pw", "lprq-1-1", "lprq-2-1", "lprq-congestion-pw", "lprq-congestion-1-1", "lprq-congestion-2-1", "energy-lprq"]