extend = [
    {path = "msq_benchmarks.toml"},
    {path = "lprq_benchmarks.toml"},
    {path = "lprq_arc_benchmarks.toml"},
    {path = "lprq_epoch_benchmarks.toml"},
    {path = "lprq_leak_benchmarks.toml"}
]

# Pairwise benchmarking, threads varies, fixed operations
[tasks.parameter-scan-pw]
description = "Hyperfine parameter scan over threads"
script = [
    "export OUTPUT=${RESULT_DIR}/${FILE}",
    "export MAX_THREADS=$(($(nproc) / $FACTOR))",
    "echo '\n'===========================================",
    "echo Parameter scan over threads",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Interval: [1, ${MAX_THREADS}]",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "hyperfine --parameter-scan Threads 1 ${MAX_THREADS} '${BINARY} {Threads} ${LOGN} ${EVEN_CORES} ${CONGESTION}' --export-json ${OUTPUT}"
]
private = true

# MPMC benchmark, thread varies, fixed operations
[tasks.parameter-scan-mpmc]
description = "Base MPMC benchmark parameter scan"
script_runner = "bash"
script = [
    # Extract how many iterations hyperfine will execute run for each ratio, also min & max threads.
    '''
    max_threads=$(($(nproc) / $FACTOR))

    # Extract the multipliers from the ratio
    IFS=':' read producer_multiplier consumer_multiplier <<< "$RATIO"

    min_threads=$((producer_multiplier + consumer_multiplier))
    iterations=$(($max_threads / $min_threads))

    export MAX_THREADS=$max_threads
    export MIN_THREADS=$min_threads
    export ITERATIONS=$iterations
    export PROD_MULTI=$producer_multiplier
    export CONS_MULTI=$consumer_multiplier
    ''',

    "echo '\n'===========================================",
    "echo Parameter scan over threads",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Interval: [${MIN_THREADS}, ${MAX_THREADS}]",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "bash ${SCRIPT_DIR}/ratio_benchmarks.sh ${PROD_MULTI} ${CONS_MULTI} ${ITERATIONS} ${FILE} ${CONGESTION}"

]
private = true

# MPMC energy consumption benchmark
[tasks.energy-consumption]
description = "Measure the energy consumption of the LPRQ"
script_runner = "bash"
script = [
    "source ${SCRIPT_DIR}/setup_ratio.sh $FACTOR $RATIO",
    "export OUTPUT=${RESULT_DIR}/${FILE}",
    "echo '\n'===========================================",
    "echo Energy consumption benchmark",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Runs: ${RUNS}",
    "echo ' ' Producers: ${PROD}",
    "echo ' ' Consumers: ${CONS}",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "perf stat -r ${RUNS} -e ${EVENTS} -o ${OUTPUT} ${BINARY} ${PROD} ${CONS} ${LOGN} ${EVEN_CORES} ${CONGESTION} >/dev/null"
]
private = true

# Congestion benchmark
[tasks.paramter-scan-congestion]
description = "Hyperfine parameter scan over congestions"
script = [
    "export THREADS=$(($(nproc) / $FACTOR))",
    "echo '\n'===========================================",
    "echo Parameter scan over congestions",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Congestions: [0.0, 0.25, 1.0]",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Threads: ${THREADS}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "bash ${SCRIPT_DIR}/congestion_benchmarks.sh ${WORKLOAD} ${FILE}"]
private = true

# Memory usage (perf) benchmark
[tasks.memory-usage]
description = "Measure the memory usage of the LPRQ"
script_runner = "bash"
script = [
    "source ${SCRIPT_DIR}/setup_ratio.sh $FACTOR $RATIO",
    "export OUTPUT=${RESULT_DIR}/${FILE}",
    "echo '\n'===========================================",
    "echo Memory usage benchmark using perf",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Runs: ${RUNS}",
    "echo ' ' Producers: ${PROD}",
    "echo ' ' Consumers: ${CONS}",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "perf stat -r ${RUNS} -B -e ${EVENTS_MEM} -o ${OUTPUT} ${BINARY} ${PROD} ${CONS} ${LOGN} ${EVEN_CORES} ${CONGESTION} >/dev/null"
]
private = true

# Memory usage (valgrind) benchmark
[tasks.valgrind-massif]
description = "Measure the memory usage of the LPRQ"
script_runner = "bash"
script = [
    "source ${SCRIPT_DIR}/setup_ratio.sh $FACTOR $RATIO",
    "export OUTPUT=${RESULT_DIR}/${FILE}",
    "echo '\n'===========================================",
    "echo Memory usage benchmark using valgrind",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Producers: ${PROD}",
    "echo ' ' Consumers: ${CONS}",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "valgrind --tool=massif --stacks=yes --massif-out-file=${OUTPUT} ${BINARY} ${PROD} ${CONS} ${LOGN} ${EVEN_CORES} ${CONGESTION} >/dev/null"
]
private = true

# Memory usage (memusage) benchmark
[tasks.memusage]
description = "Measure the memory usage of the LPRQ"
script_runner = "bash"
script = [
    "source ${SCRIPT_DIR}/setup_ratio.sh $FACTOR $RATIO",
    "export OUTPUT=${RESULT_DIR}/${FILE}",
    "echo '\n'===========================================",
    "echo Memory usage benchmark using memusage",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Producers: ${PROD}",
    "echo ' ' Consumers: ${CONS}",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores: ${EVEN_CORES}",
    "echo ' ' Congestion: ${CONGESTION}'\n'",
    "memusage ${BINARY} ${PROD} ${CONS} ${LOGN} ${EVEN_CORES} ${CONGESTION} > ${OUTPUT} 2>&1"
]
private = true