extend = [
    {path = "msq_benchmarks.toml"},
    {path = "lprq_benchmarks.toml"}
]

# Pairwise benchmarking, threads varies, fixed operations
[tasks.parameter-scan-pairwise-threads]
description = "Hyperfine parameter scan over threads"
script = [
    "export MAX_THREADS=$(($(nproc) / $FACTOR))",
    "echo '\n'===========================================",
    "echo Parameter scan over threads'\n' Workload and Queue: $TARGET'\n' Interval: [1, $MAX_THREADS]'\n' Operations: 10^$LOGN",
    "hyperfine --parameter-scan num_threads 1 $MAX_THREADS '$BINARY {num_threads} $LOGN' --export-json ${RESULT_DIR}/$JSON"
]
private = true

# Pairwise benchmarking, operations varies, fixed threads
[tasks.parameter-scan-pairwise-ops]
description = "Hyperfine parameter scan over operations"
script = [
    "echo '\n'===========================================",
    "echo Parameter scan over log\\(N\\)'\n' Workload and Queue: $TARGET'\n' Interval: [${MIN_LOGN}, ${MAX_LOGN}] '\n' Threads: $THREADS",
    "hyperfine --parameter-scan num_ops ${MIN_LOGN} ${MAX_LOGN} '$BINARY ${THREADS} {num_ops}' --export-json ${RESULT_DIR}/$JSON"
]
private = true

# TODO: MPMC benchmarking 1:1 producer:consumer ratio
[tasks.parameter-scan-mpmc-1-1]
description = ""
script = [
    "echo '\n'===========================================",
    "echo ",
]
private = true

# TODO: MPMC benchmarking 2:1 producer:consumer ratio
[tasks.parameter-scan-mpmc-2-1]
description = ""
script = [
    "echo '\n'===========================================",
    "echo ",
]
private = true

# TODO: MPMC benchmarking 1:2 producer:consumer ratio
[tasks.parameter-scan-mpmc-1-2]
description = ""
script = [
    "echo '\n'===========================================",
    "echo ",
]
private = true