extend = [
    {path = "msq_benchmarks.toml"},
    {path = "lprq_benchmarks.toml"}
]

# Pairwise benchmarking, threads varies, fixed operations
[tasks.parameter-scan-pairwise-threads]
description = "Hyperfine parameter scan over threads"
script = [
    "export MAX_THREADS=$(($(nproc) / FACTOR))",
    "echo '\n'===========================================",
    "echo Parameter scan over threads",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Interval: [1, ${MAX_THREADS}]",
    "echo ' ' Operations: 10^${LOGN}",
    "echo ' ' Even cores only: ${EVEN_CORES}'\n'",
    "hyperfine --parameter-scan num_threads 1 ${MAX_THREADS} '${BINARY} {num_threads} ${LOGN} ${EVEN_CORES}' --export-json ${RESULT_DIR}/$JSON"
]
private = true


# Pairwise benchmarking, operations varies, fixed threads 
[tasks.parameter-scan-pairwise-ops]
description = "Hyperfine parameter scan over operations"
script = [
    "echo '\n'===========================================",
    "export THREADS=$(($(nproc) / (FACTOR*2)))",
    "echo Parameter scan over logn",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Interval: [${MIN_LOGN}, ${MAX_LOGN}]",
    "echo ' ' Threads: ${THREADS}",
    "echo ' ' Even cores only: ${EVEN_CORES}'\n'",
    "hyperfine --parameter-scan num_ops ${MIN_LOGN} ${MAX_LOGN} '${BINARY} ${THREADS} {num_ops} ${EVEN_CORES}' --export-json ${RESULT_DIR}/$JSON"
]
private = true

# MPMC benchmark, thread varies, fixed operations
[tasks.parameter-scan-mpmc]
description = "Base MPMC benchmark parameter scan"
script_runner = "bash"
script = [
    "echo RATIO: ${RATIO}, DIVISOR: ${DIVISOR}, MIN_THREADS: ${MIN_THREADS}",
    "export MAX_THREADS=$(($(nproc) / FACTOR))",
    "export MAX_ITER=$((MAX_THREADS / $DIVISOR))",
    "echo '\n'===========================================",
    "echo Parameter scan over threads",
    "echo ' ' Benchmark: $TARGET",
    "echo ' ' Interval: [${MIN_THREADS}, ${MAX_THREADS}]",
    "echo ' ' Operations: 10^$LOGN",
    "echo ' ' Even cores only: ${EVEN_CORES}'\n'",
    "bash ./makefiles/ratio_benchmarks.sh ${RATIO} ${MAX_ITER}"

]
private = true
