# Pairwise benchmarks (Rust)
[tasks.pw-lprq-rust]
extend = "parameter-scan-pw"
env = { TARGET = "pw LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pw", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PW_JSON}"}
private = true

# pw benchmarks (C)
[tasks.pw-lprq-c]
extend = "parameter-scan-pw"
env = { TARGET = "pw LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pw", CONGESTION = "0.0", FILE = "${C_LPRQ_PW_JSON}"}
private = true

# MPMC benchmarks (Rust)
[tasks.mpmc-lprq-rust-1-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PC_JSON_11}",  RATIO = "1:1"}
private = true
[tasks.mpmc-lprq-rust-2-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PC_JSON_21}", RATIO = "2:1"}
private = true
[tasks.mpmc-lprq-rust-1-2]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:2 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PC_JSON_12}", RATIO = "1:2"}
private = true

# MPMC benchmarks (C)
[tasks.mpmc-lprq-c-1-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:1 LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", CONGESTION = "0.0", FILE = "${C_LPRQ_PC_JSON_11}",  RATIO = "1:1" }
private = true
[tasks.mpmc-lprq-c-2-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 2:1 LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", CONGESTION = "0.0", FILE = "${C_LPRQ_PC_JSON_21}", RATIO = "2:1"}
private = true
[tasks.mpmc-lprq-c-1-2]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:2 LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", CONGESTION = "0.0", FILE = "${C_LPRQ_PC_JSON_12}",  RATIO = "1:2" }
private = true

# MPMC energy consumption benchmarks using perf (Rust) 
[tasks.energy-rust-1-1]
extend = "energy-consumption"
env = {TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${RUST_ENERGY_11}"}
private=true
[tasks.energy-rust-2-1] 
extend = "energy-consumption"
env = {TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${RUST_ENERGY_21}"}
private=true

# MPMC energy consumption benchmarks using perf (C++)
[tasks.energy-c-1-1]
extend = "energy-consumption"
env = {TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${C_ENERGY_11}"}
private=true
[tasks.energy-c-2-1] 
extend = "energy-consumption"
env = {TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${C_ENERGY_21}"}
private=true

# MPMC memory usage benchmarks using perf (Rust) 
[tasks.memory-rust-1-1]
extend = "memory-usage"
env = {TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${RUST_MEM_11}"}
private=true
[tasks.memory-rust-2-1] 
extend = "memory-usage"
env = {TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${RUST_MEM_21}"}
private=true

# MPMC memory usage benchmarks using perf (C++)
[tasks.memory-c-1-1]
extend = "memory-usage"
env = {TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${C_MEM_11}"}
private=true
[tasks.memory-c-2-1] 
extend = "memory-usage"
env = {TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${C_MEM_21}"}
private=true

# MPMC memory usage benchmarks using valgrind (Rust) 
[tasks.valgrind-rust-1-1]
extend = "valgrind-massif"
env = {TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${RUST_VALG_11}"}
private=true
[tasks.valgrind-rust-2-1] 
extend = "valgrind-massif"
env = {TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${RUST_VALG_21}"}
private=true

# MPMC memory usage benchmarks using valgrind (C++)
[tasks.valgrind-c-1-1]
extend = "valgrind-massif"
env = {TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${C_VALG_11}"}
private=true
[tasks.valgrind-c-2-1] 
extend = "valgrind-massif"
env = {TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${C_VALG_21}"}
private=true

# MPMC memory usage benchmarks using memusage (Rust) 
[tasks.memusage-rust-1-1]
extend = "memusage"
env = {TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${RUST_MEMUSAGE_11}"}
private=true
[tasks.memusage-rust-2-1] 
extend = "memusage"
env = {TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${RUST_MEMUSAGE_21}"}
private=true

# MPMC memory usage benchmarks using memusage (C++)
[tasks.memusage-c-1-1]
extend = "memusage"
env = {TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${C_MEMUSAGE_11}"}
private=true
[tasks.memusage-c-2-1] 
extend = "memusage"
env = {TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${C_MEMUSAGE_21}"}
private=true

# Congestion benchmarks (Rust)
[tasks.congestion-pw-lprq-rust]
extend = "paramter-scan-congestion"
env = { TARGET = "pw LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pw", WORKLOAD = "pw", FILE = "${RUST_LPRQ_PW_CONGESTION_JSON}"}
[tasks.congestion-mpmc-rust-1-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", WORKLOAD = "mpmc-1:1", FILE = "${RUST_PC_CONGESTION_JSON_11}"}
[tasks.congestion-mpmc-rust-2-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", WORKLOAD = "mpmc-2:1", FILE = "${RUST_PC_CONGESTION_JSON_21}"}

# Congestion benchmarks (C++)
[tasks.congestion-pw-lprq-c]
extend = "paramter-scan-congestion"
env = { TARGET = "pw LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pw", WORKLOAD = "pw", FILE = "${C_LPRQ_PW_CONGESTION_JSON}"}
[tasks.congestion-mpmc-c-1-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", WORKLOAD = "mpmc-1:1", FILE = "${C_PC_CONGESTION_JSON_11}"}
[tasks.congestion-mpmc-c-2-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", WORKLOAD = "mpmc-2:1", FILE = "${C_PC_CONGESTION_JSON_21}"}

