# Pairwise benchmarks
[tasks.pw-lprq-arc]
extend = "parameter-scan-pw"
env = { TARGET = "Pairwise LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_pairwise", CONGESTION = "0.0", FILE = "${ARC_PW_JSON}"}
private = true

# MPMC benchmarks
[tasks.mpmc-lprq-arc-1-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", CONGESTION = "0.0", FILE = "${ARC_PC_JSON_11}",  RATIO = "1:1"}
private = true
[tasks.mpmc-lprq-arc-2-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 2:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", CONGESTION = "0.0", FILE = "${ARC_PC_JSON_21}", RATIO = "2:1"}
private = true
[tasks.mpmc-lprq-arc-1-2]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:2 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", CONGESTION = "0.0", FILE = "${ARC_PC_JSON_12}",  RATIO = "1:2" }
private = true

# MPMC energy consumption benchmarks
[tasks.energy-arc-1-1]
extend = "energy-consumption"
env = {TARGET = "MPMC 1:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${ARC_ENERGY_11}"}
private=true
[tasks.energy-arc-2-1] 
extend = "energy-consumption"
env = {TARGET = "MPMC 2:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${ARC_ENERGY_21}"}
private=true

# MPMC memory usage benchmarks using perf
[tasks.memory-arc-1-1]
extend = "memory-usage"
env = {TARGET = "MPMC 1:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${ARC_MEM_11}"}
private=true
[tasks.memory-arc-2-1] 
extend = "memory-usage"
env = {TARGET = "MPMC 2:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${ARC_MEM_21}"}
private=true

# MPMC memory usage benchmarks using valgrind
[tasks.valgrind-arc-1-1]
extend = "valgrind-massif"
env = {TARGET = "MPMC 1:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${ARC_VALG_11}"}
private=true
[tasks.valgrind-arc-2-1] 
extend = "valgrind-massif"
env = {TARGET = "MPMC 2:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${ARC_VALG_21}"}
private=true

# MPMC memory usage benchmarks using memusage
[tasks.memusage-arc-1-1]
extend = "memusage"
env = {TARGET = "MPMC 1:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${ARC_MEMUSAGE_11}"}
private=true
[tasks.memusage-arc-2-1] 
extend = "memusage"
env = {TARGET = "MPMC 2:1 LPRQ (Rust Arc)", BINARY = "${RUST_DIR}/target/release/lprq_arc_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${ARC_MEMUSAGE_21}"}
private=true
