# Pairwise benchmarks (Rust)
[tasks.pairwise-lprq-rust-t]
extend = "parameter-scan-pairwise-threads"
env = { TARGET = "Pairwise LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pairwise", JSON = "${RUST_LPRQ_PW_JSON_T}"}
private = true
[tasks.pairwise-lprq-rust-o]
extend = "parameter-scan-pairwise-ops"
env = { TARGET = "Pairwise LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pairwise", JSON = "${RUST_LPRQ_PW_JSON_O}"}
private = true

# Pairwise benchmarks (C)
[tasks.pairwise-lprq-c-t]
extend = "parameter-scan-pairwise-threads"
env = { TARGET = "Pairwise LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pairwise", JSON = "${C_LPRQ_PW_JSON_T}"}
private = true
[tasks.pairwise-lprq-c-o]
extend = "parameter-scan-pairwise-ops"
env = { TARGET = "Pairwise LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pairwise", JSON = "${C_LPRQ_PW_JSON_O}"}
private = true
 
# TODO: MPMC benchmarks (Rust)
[tasks.mpmc-lprq-rust]
# extend = "parameter-scan-pairwise-threads"
# env = { TARGET = "MPMC LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", JSON = "${RUST_LPRQ_PC_JSON_T}"}
# private = true
# [tasks.mpmc-lprq-rust-o]
# extend = "parameter-scan-pairwise-ops"
# env = { TARGET = "MPMC LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", JSON = "${RUST_LPRQ_PC_JSON_O}"}
# private = true

# TODO: MPMC benchmarks (C)
[tasks.mpmc-lprq-c]
# extend = "parameter-scan-pairwise-threads"
# env = { TARGET = "MPMC LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", JSON = "${C_LPRQ_PC_JSON_T}"}
# private = true
# [tasks.mpmc-lprq-c-o]
# extend = "parameter-scan-pairwise-ops"
# env = { TARGET = "MPMC LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", JSON = "${C_LPRQ_PC_JSON_O}"}
# private = true

# Commands for Pairwise benchmarks (Rust and C)
[tasks.benchmark-pairwise-lprq-t]
description = "Parameter scan over threads for pairwise LPRQ"
dependencies = ["pairwise-lprq-c-t", "pairwise-lprq-rust-t"]
[tasks.benchmark-pairwise-lprq-o]
description = "Parameter scan over operations for pairwise LPRQ"
dependencies = ["pairwise-lprq-c-o", "pairwise-lprq-rust-o"]
[tasks.benchmark-pairwise-lprq]
description = "Parameter scan for pairwise LPRQ"
dependencies = ["benchmark-pairwise-lprq-t", "benchmark-pairwise-lprq-o"]

# TODO: Commands for MPMC benchmarks (Rust and C)
[tasks.benchmark-mpmc-lprq]

# Command for Pairwise and MPMC benchmarks
[tasks.benchmark-lprq]
description = "All benchmarks for LPRQ"
dependencies = ["benchmark-pairwise-lprq", "benchmark-mpmc-lprq"]