# Pairwise benchmarks (Rust)
[tasks.pairwise-lprq-rust]
extend = "parameter-scan-pairwise"
env = { TARGET = "Pairwise LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pairwise", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PW_JSON}"}
private = true

# Pairwise benchmarks (C)
[tasks.pairwise-lprq-c]
extend = "parameter-scan-pairwise"
env = { TARGET = "Pairwise LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pairwise", CONGESTION = "0.0", FILE = "${C_LPRQ_PW_JSON}"}
private = true

# MPMC benchmarks (Rust)
[tasks.mpmc-lprq-rust-1-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PC_JSON_11}",  RATIO = "1:1"}
private = true
[tasks.mpmc-lprq-rust-2-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", CONGESTION = "0.0", FILE = "${RUST_LPRQ_PC_JSON_21}", RATIO = "2:1"}
private = true

# MPMC benchmarks (C)
[tasks.mpmc-lprq-c-1-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 1:1 LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", CONGESTION = "0.0", FILE = "${C_LPRQ_PC_JSON_11}",  RATIO = "1:1" }
private = true
[tasks.mpmc-lprq-c-2-1]
extend = "parameter-scan-mpmc"
env = { TARGET = "MPMC 2:1 LPRQ (C)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", CONGESTION = "0.0", FILE = "${C_LPRQ_PC_JSON_21}", RATIO = "2:1"}
private = true

# MPMC energy consumption benchmarks (Rust) 
[tasks.energy-rust-1-1]
extend = "energy-consumption"
env = {TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${RUST_ENERGY_11}"}
private=true
[tasks.energy-rust-2-1] 
extend = "energy-consumption"
env = {TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${RUST_ENERGY_21}"}
private=true

# MPMC energy consumption benchmarks (C++)
[tasks.energy-c-1-1]
extend = "energy-consumption"
env = {TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "1:1", CONGESTION = "0.0", FILE = "${C_ENERGY_11}"}
private=true
[tasks.energy-c-2-1] 
extend = "energy-consumption"
env = {TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", RATIO = "2:1", CONGESTION = "0.0", FILE = "${C_ENERGY_21}"}
private=true

# Congestion benchmarks (Rust)
[tasks.congestion-pairwise-lprq-rust]
extend = "paramter-scan-congestion"
env = { TARGET = "Pairwise LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_pairwise", WORKLOAD = "pairwise", FILE = "${RUST_LPRQ_PW_CONGESTION_JSON}"}
[tasks.congestion-mpmc-rust-1-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 1:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", WORKLOAD = "mpmc-1:1", FILE = "${RUST_PC_CONGESTION_JSON_11}"}
[tasks.congestion-mpmc-rust-2-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 2:1 LPRQ (Rust)", BINARY = "${RUST_DIR}/target/release/lprq_mpmc", WORKLOAD = "mpmc-2:1", FILE = "${RUST_PC_CONGESTION_JSON_21}"}

# Congestion benchmarks (C++)
[tasks.congestion-pairwise-lprq-c]
extend = "paramter-scan-congestion"
env = { TARGET = "Pairwise LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-pairwise", WORKLOAD = "pairwise", FILE = "${C_LPRQ_PW_CONGESTION_JSON}"}
[tasks.congestion-mpmc-c-1-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 1:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", WORKLOAD = "mpmc-1:1", FILE = "${C_PC_CONGESTION_JSON_11}"}
[tasks.congestion-mpmc-c-2-1]
extend = "paramter-scan-congestion"
env = { TARGET = "MPMC 2:1 LPRQ (C++)", BINARY = "${C_LPRQ_DIR}/build/bench-lprq-mpmc", WORKLOAD = "mpmc-2:1", FILE = "${C_PC_CONGESTION_JSON_21}"}

