
# Pairwise comparison between Rust and C
[tasks._graph-pairwise-msq]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PW_JSON}", C_JSON = "${C_MSQ_PW_JSON}", FILE = "${MSQ_GRAPH_PW}", FLAGS="", LEGEND="Rust,C"}
[tasks.graph-pairwise-msq]
dependencies = ["_graph-pairwise-msq"]
