
# Pairwise comparison between Rust and C
[tasks._graph-pairwise-msq-t]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PW_JSON_T}", C_JSON = "${C_MSQ_PW_JSON_T}", FILE = "${MSQ_GRAPH_PW_T}", FLAGS="", LEGEND="Rust,C"}
[tasks.graph-pairwise-msq-t]
dependencies = ["_graph-pairwise-msq-t"]
[tasks._graph-pairwise-msq-o]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PW_JSON_O}", C_JSON = "${C_MSQ_PW_JSON_O}", FILE = "${MSQ_GRAPH_PW_O}", FLAGS="--log-time", LEGEND="Rust,C"}
[tasks.graph-pairwise-msq-o]
dependencies = ["_graph-pairwise-msq-o"]