
# Pairwise comparison between Rust and C
[tasks._graph-pairwise-msq-t]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PW_JSON_T}", C_JSON = "${C_MSQ_PW_JSON_T}", FILE = "${MSQ_GRAPH_PW_T}"}
[tasks.graph-pairwise-msq-t]
dependencies = ["_graph-pairwise-msq-t"]
[tasks._graph-pairwise-msq-o]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PW_JSON_O}", C_JSON = "${C_MSQ_PW_JSON_O}", FILE = "${MSQ_GRAPH_PW_O}"}
[tasks.graph-pairwise-msq-o]
dependencies = ["_graph-pairwise-msq-o"]

# MPMC comparison between Rust and C
[tasks._graph-mpmc-msq-t]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PC_JSON_T}", C_JSON = "${C_MSQ_PC_JSON_T}", FILE = "${MSQ_GRAPH_PC_T}"}
[tasks.graph-mpmc-msq-t]
dependencies = ["_graph-mpmc-msq-t"]
[tasks._graph-mpmc-msq-o]
extend = "create-graph"
env = {SCRIPT = "${PARAM_PLOT}", RUST_JSON = "${RUST_MSQ_PC_JSON_O}", C_JSON = "${C_MSQ_PC_JSON_O}", FILE = "${MSQ_GRAPH_PC_O}"}
[tasks.graph-mpmc-msq-o]
dependencies = ["_graph-mpmc-msq-o"]

# Pairwise and MPMC graphs
[tasks.graph-msq]
description = "All graphs for MSQ"
dependencies = ["graph-pairwise-msq-t", "graph-mpmc-msq-t", "graph-pairwise-msq-o", "graph-mpmc-msq-o"]