# Pairwise benchmarks (Rust)
[tasks.pairwise-msq-rust-t]
extend = "parameter-scan-pairwise-threads"
env = { TARGET = "Pairwise MSQ (Rust)", BINARY = "${RUST_DIR}/target/release/msq_pairwise", JSON = "${RUST_MSQ_PW_JSON_T}" }
private = true
[tasks.pairwise-msq-rust-o]
extend = "parameter-scan-pairwise-ops"
env = { TARGET = "Pairwise MSQ (Rust)", BINARY = "${RUST_DIR}/target/release/msq_pairwise", JSON = "${RUST_MSQ_PW_JSON_O}" }
private = true

# Pairwise benchmarks (C)
[tasks.pairwise-msq-c-t]
extend = "parameter-scan-pairwise-threads"
env = { TARGET = "Pairwise MSQ (C)", BINARY = "${C_MSQ_DIR}/msqueue", JSON = "${C_MSQ_PW_JSON_T}" }
private = true
[tasks.pairwise-msq-c-o]
extend = "parameter-scan-pairwise-ops"
env = { TARGET = "Pairwise MSQ (C)", BINARY = "${C_MSQ_DIR}/msqueue", JSON = "${C_MSQ_PW_JSON_O}" }
private = true

# TODO: MPMC benchmarks (Rust)
[tasks.mpmc-msq-rust]
# extend = "parameter-scan-pairwise-threads"
# env = { TARGET = "MPMC MSQ (Rust)", BINARY = "${RUST_DIR}/target/release/msq_mpmc", JSON = "${RUST_MSQ_PC_JSON_T}"}
# private = true
# [tasks.mpmc-msq-rust-o]
# extend = "parameter-scan-pairwise-ops"
# env = { TARGET = "MPMC MSQ (Rust)", BINARY = "${RUST_DIR}/target/release/msq_mpmc", JSON = "${RUST_MSQ_PC_JSON_O}"}
# private = true

# TODO: MPMC benchmarks (C)
[tasks.mpmc-msq-c]
# extend = "parameter-scan-pairwise-threads"
# env = { TARGET = "MPMC MSQ (C)", BINARY = "${C_MSQ_DIR}/msqueue", JSON = "${C_MSQ_PC_JSON_T}"}
# private = true
# [tasks.mpmc-msq-c-o]
# extend = "parameter-scan-pairwise-ops"
# env = { TARGET = "MPMC MSQ (C)", BINARY = "${C_MSQ_DIR}/msqueue", JSON = "${C_MSQ_PC_JSON_O}"}
# private = true

