# Pairwise benchmarks (Rust)
[tasks.pairwise-msq-rust]
extend = "parameter-scan-pairwise"
env = { TARGET = "Pairwise MSQ (Rust)", BINARY = "${RUST_DIR}/target/release/msq_pairwise", CONGESTION = "0.0", FILE = "${RUST_MSQ_PW_JSON}" }
private = true

# Pairwise benchmarks (C)
[tasks.pairwise-msq-c]
extend = "parameter-scan-pairwise"
env = { TARGET = "Pairwise MSQ (C)", BINARY = "${C_MSQ_DIR}/msqueue", CONGESTION = "0.0", FILE = "${C_MSQ_PW_JSON}" }
private = true