extend = [
    {path = "./msq_plots.toml"},
    {path = "./lprq_plots.toml"},
    {path = "./arc_plots.toml"}
]

# Generic task for creating graphs
[tasks.create-graph]
description = "Outputs a .png of the graph"
script_runner = "bash"
script = [
    '''
    IFS=',' read -r -a input_files <<< "$INPUT"
    for input_file in "${input_files[@]}"
    do
        input+="${RESULT_DIR}/${input_file} "
    done

    mkdir -p $GRAPH_DIR

    python3 ${SCRIPT_DIR}/${SCRIPT} $input -o ${GRAPH_DIR}/${FILE} ${FLAGS} --titles ${LEGEND}
    '''

]
private = true

[tasks.create-table]
description = "Create table from memory and energy benchmakrs"
script_runner = "bash"
script = [
    "python3 ${SCRIPT_DIR}/create_table.py ${RESULT_DIR}"
]

