extend = [
    {path = "./msq_plots.toml"},
    {path = "./lprq_plots.toml"}
]

# Generic task for creating graphs
[tasks.create-graph]
description = "Outputs a .png of the graph"
category = "Utility"
script_runner = "bash"
script = [
    "python3 ${SCRIPT_DIR}/${SCRIPT} ${RESULT_DIR}/${RUST_JSON} ${RESULT_DIR}/${C_JSON} -o ${RESULT_DIR}/${FILE} ${FLAGS} --titles Rust,C"
]
private = true

